# Load RUCKUS library
source -quiet $::env(RUCKUS_DIR)/vivado_proc.tcl

# Load Source Code
loadSource -lib lcls_timing_core -path "$::DIR_PATH/rtl/TimingPkg.vhd"
loadSource -lib lcls_timing_core -path "$::DIR_PATH/rtl/TPGPkg.vhd"
loadSource -lib lcls_timing_core -path "$::DIR_PATH/rtl/TPGMiniReg.vhd"
loadSource -lib lcls_timing_core -path "$::DIR_PATH/rtl/Divider.vhd"
loadSource -lib lcls_timing_core -path "$::DIR_PATH/rtl/BsaControlv2.vhd"
loadSource -lib lcls_timing_core -path "$::DIR_PATH/rtl/CtrControl.vhd"
loadSource -lib lcls_timing_core -path "$::DIR_PATH/rtl/ClockTime.vhd"
loadSource -lib lcls_timing_core -path "$::DIR_PATH/rtl/EventSelect.vhd"
loadSource -lib lcls_timing_core -path "$::DIR_PATH/rtl/TPSerializer.vhd"
loadSource -lib lcls_timing_core -path "$::DIR_PATH/rtl/TPGMini.vhd"
loadSource -lib lcls_timing_core -path "$::DIR_PATH/rtl/TPGMiniEdef.vhd"
loadSource -lib lcls_timing_core -path "$::DIR_PATH/rtl/TPGMiniEdefPkg.vhd"
loadSource -lib lcls_timing_core -path "$::DIR_PATH/rtl/TPGMiniCore.vhd"
loadSource -lib lcls_timing_core -path "$::DIR_PATH/rtl/TPGMiniStream.vhd"
loadSource -lib lcls_timing_core -path "$::DIR_PATH/rtl/TimingSerializer.vhd"
loadSource -lib lcls_timing_core -path "$::DIR_PATH/rtl/TimingDeserializer.vhd"
loadSource -lib lcls_timing_core -path "$::DIR_PATH/rtl/TimingSerialDelay.vhd"
loadSource -lib lcls_timing_core -path "$::DIR_PATH/rtl/TimingRx.vhd"
loadSource -lib lcls_timing_core -path "$::DIR_PATH/rtl/TimingFrameRx.vhd"
loadSource -lib lcls_timing_core -path "$::DIR_PATH/rtl/TimingStreamRx.vhd"
loadSource -lib lcls_timing_core -path "$::DIR_PATH/rtl/TimingStreamTx.vhd"
loadSource -lib lcls_timing_core -path "$::DIR_PATH/rtl/GthRxAlignCheck.vhd"
loadSource -lib lcls_timing_core -path "$::DIR_PATH/rtl/TimingMsgAxiRingBuffer.vhd"
loadSource -lib lcls_timing_core -path "$::DIR_PATH/rtl/TimingMsgDelay.vhd"
loadSource -lib lcls_timing_core -path "$::DIR_PATH/rtl/TimingMsgToAxiStream.vhd"
loadSource -lib lcls_timing_core -path "$::DIR_PATH/rtl/TimingCore.vhd"
loadSource -lib lcls_timing_core -path "$::DIR_PATH/rtl/EthTimingModule.vhd"
loadSource -lib lcls_timing_core -path "$::DIR_PATH/rtl/BldAxiStream.vhd"
loadSource -lib lcls_timing_core -path "$::DIR_PATH/rtl/WordSerializer.vhd"
