package:
  name: lcls_timing_core
  version: {{ GIT_DESCRIBE_TAG }}

source:
   path: ..

build:
   number: {{ GIT_DESCRIBE_NUMBER|int }}
   noarch: python

requirements:
   build:
     - python>=3.7
     - rogue
     - git
     - gitpython
     - numpy

   run:
     - python>=3.7
     - rogue
     - numpy

about:
   home: https://github.com/slaclab/lcls-timing-core
   license: SLAC Open License
   license_file: LICENSE.txt
   summary: LCLS Timing Core Library

